name: farmers
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro # her dosyanın ciktisini yeniden üretecek
          git fetch --prune
          dvc metrics diff --show-md master

          # resim çıktılarını ekliyoruz
          echo '![](./by_region.png )' >> report.md
          cml comment create report.md