name: farmers
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt      
          dvc repro
          echo "## Model Metrics" > report.md
          cat metrics.json >> report.md
          echo "## Validating results by region"
          echo '![](./by_region.png )' >> report.md
          cml comment create report.md