name: farmers
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc pull data --run-cache        
          dvc repro 

          git fetch --depth=1 origin main:main


          dvc metrics diff --show-md main


          echo '![](./by_region.png )' >> report.md
          cml comment create report.md